### ISSUE TITLE
Win rate standard deviation as indicator for civ balance quality by patch

### ISSUE THREAD

**Issue by curry2810** [jerkeeler/aoestats-frontend#2]
First of, thanks for the great work with aoestats.io!

Your stats would be a great basis for adding the standard deviation of win rate and play rate. This could be a very helpful indicator for the civ balance quality per patch, especially if you compare it for different patches over time.

**Comment by jerkeeler** [comment]
Hi, thanks for visiting my website! I'm glad you like it! 

I have considered adding standard deviation, but part of me thinks it might be confusing for your average user? I'm trying to walk a line between usability and pertinent information. I do think I need to add something in terms of standard deviation and/or population size. I'm still working on some graphical ideas on how to convey that. Any suggestions are welcome :)
