### ISSUE TITLE
Median instead of average for game length. 

### ISSUE THREAD

**Issue by Moldrim** [jerkeeler/aoestats-frontend#6]
Hi, 

First of thanks for all these wonderfull stats! 

I think there are some truly long games out there which skew the average game length for civs. 

Would it be possible to get the median instead of the average just to get a feeling on how long the games are?

Also having the game length in the matchup view might be interesting.

**Comment by jerkeeler** [comment]
I will do this if the average starts to look too skewed. For now it's ok.
