### ISSUE TITLE
Confusing wording in the FAQ section.

### ISSUE THREAD

**Issue by yellow** [jerkeeler/aoestats-frontend#8]
> Q: How can I support you?
> 
> Awwwww thanks! 😊 You can support me by **buying me a coffee!** Just click the big orange button in the navbar. Any donations will go **strictly toward hosting costs**.
> 

People may not realize that the donation website is called buymeacoffee.com
Great website by the way, keep it up!

**Comment by jerkeeler** [comment]
Thanks for the info! I'll update the FAQ to have a direct link to make it clearer. Glad you like the website!
